import { Product, QuizQuestion, DailyTip, Subscription, Review } from './types';

export const products: Product[] = [
  // VASTU REMEDY KITS
  {
    id: 'v1',
    name: 'Vastu Dosh Nivaran Kit',
    nameHindi: 'वास्तु दोष निवारण किट',
    category: 'vastu',
    subCategory: 'Dosh Nivaran',
    price: 2499,
    originalPrice: 3999,
    discount: 38,
    rating: 4.8,
    reviews: 324,
    image: './images/vastu-kit.jpg',
    images: ['./images/vastu-kit.jpg', './images/puja-kit.jpg'],
    description: 'Complete Vastu Dosh Nivaran Kit to neutralize negative energies and restore harmony in your home. Energized by Vedic pandits with authentic mantras.',
    includes: ['Vastu Yantra (Copper)', 'Vastu Pyramid Set (5 pcs)', 'Rock Salt Crystal', 'Camphor Tablets', 'Sacred Thread (Mauli)', 'Guggul Dhoop', 'Instruction Booklet', 'Energized Water Vessel'],
    benefits: ['Removes Vastu defects from home', 'Brings peace and prosperity', 'Protects from negative energies', 'Improves family harmony', 'Enhances positive vibrations'],
    instructions: ['Clean the area with Gangajal', 'Place Yantra in the center of home', 'Arrange pyramids in 5 directions', 'Light Guggul Dhoop', 'Recite the provided mantras 11 times', 'Tie sacred thread at entrance'],
    tags: ['bestseller', 'vastu', 'home'],
    isBestseller: true,
    forType: ['home'],
    inStock: true,
  },
  {
    id: 'v2',
    name: 'Griha Pravesh Kit',
    nameHindi: 'गृह प्रवेश किट',
    category: 'vastu',
    subCategory: 'New Home',
    price: 3499,
    originalPrice: 5499,
    discount: 36,
    rating: 4.9,
    reviews: 198,
    image: './images/puja-kit.jpg',
    images: ['./images/puja-kit.jpg', './images/vastu-kit.jpg'],
    description: 'Auspicious Griha Pravesh ceremony kit with all essential items for a blessed new beginning in your new home.',
    includes: ['Kalash Set (Brass)', 'Mango Leaves', 'Sacred Rice (Akshata)', 'Turmeric & Kumkum', 'Coconut', 'Ghee Lamp', 'Incense Sticks (Premium)', 'Swastik Sticker Set', 'Red Cloth', 'Gangajal Bottle'],
    benefits: ['Ensures auspicious entry', 'Purifies the new space', 'Invokes divine blessings', 'Protects from evil eye', 'Brings good fortune'],
    instructions: ['Perform at auspicious muhurta', 'Place Kalash at entrance', 'Light ghee lamp', 'Apply turmeric & kumkum at doorstep', 'Break coconut at threshold', 'Enter with right foot first'],
    tags: ['new-home', 'vastu', 'auspicious'],
    isNew: true,
    forType: ['home'],
    inStock: true,
  },
  {
    id: 'v3',
    name: 'Office Vastu Correction Kit',
    nameHindi: 'ऑफिस वास्तु किट',
    category: 'vastu',
    subCategory: 'Office',
    price: 1999,
    originalPrice: 3299,
    discount: 39,
    rating: 4.7,
    reviews: 156,
    image: './images/vastu-kit.jpg',
    images: ['./images/vastu-kit.jpg'],
    description: 'Transform your office energy with this powerful Vastu correction kit designed for professional spaces.',
    includes: ['Office Vastu Yantra', 'Crystal Globe', 'Feng Shui Tortoise', 'Lucky Bamboo Seeds', 'Desk Pyramid', 'Positive Energy Spray'],
    benefits: ['Improves productivity', 'Enhances career growth', 'Attracts opportunities', 'Reduces workplace conflicts', 'Brings financial stability'],
    instructions: ['Place Yantra on north wall', 'Keep crystal globe on desk', 'Position tortoise near entrance', 'Place pyramid on work desk', 'Spray positive energy mist weekly'],
    tags: ['office', 'vastu', 'career'],
    forType: ['office'],
    inStock: true,
  },
  {
    id: 'v4',
    name: 'Wealth & Prosperity Kit',
    nameHindi: 'धन समृद्धि किट',
    category: 'vastu',
    subCategory: 'Wealth',
    price: 2999,
    originalPrice: 4999,
    discount: 40,
    rating: 4.9,
    reviews: 412,
    image: './images/puja-kit.jpg',
    images: ['./images/puja-kit.jpg'],
    description: 'Attract wealth, abundance, and financial prosperity with this powerful Vastu remedy kit blessed by Vedic scholars.',
    includes: ['Kuber Yantra (Gold Plated)', 'Lakshmi Idol (Brass)', 'Money Plant Seeds', 'Prosperity Incense', 'Citrine Crystal', 'Green Aventurine Stone', 'Wealth Affirmation Card'],
    benefits: ['Attracts wealth and money', 'Opens new income sources', 'Removes financial blocks', 'Enhances savings', 'Brings abundance'],
    instructions: ['Place Kuber Yantra in north', 'Position Lakshmi idol in east', 'Plant money plant in southeast', 'Light prosperity incense daily', 'Keep crystals in cash box'],
    tags: ['wealth', 'vastu', 'bestseller'],
    isBestseller: true,
    forType: ['home', 'office', 'business'],
    inStock: true,
  },
  {
    id: 'v5',
    name: 'Nazar Dosh Protection Kit',
    nameHindi: 'नज़र दोष निवारण किट',
    category: 'vastu',
    subCategory: 'Protection',
    price: 1499,
    originalPrice: 2499,
    discount: 40,
    rating: 4.6,
    reviews: 267,
    image: './images/vastu-kit.jpg',
    images: ['./images/vastu-kit.jpg'],
    description: 'Shield your home and family from evil eye and negative energies with this powerful protection kit.',
    includes: ['Nazar Battu (7 Chili & Lemon)', 'Black Tourmaline Crystal', 'Evil Eye Wall Hanging', 'Protection Yantra', 'Black Salt', 'Loban Dhoop', 'Nimbu Mirchi Thread'],
    benefits: ['Protects from evil eye', 'Removes negative energy', 'Shields family members', 'Creates protective barrier', 'Wards off jealousy'],
    instructions: ['Hang Nazar Battu at entrance', 'Place tourmaline at main door', 'Burn Loban every Saturday', 'Sprinkle black salt at corners', 'Place yantra above main door'],
    tags: ['protection', 'vastu', 'home'],
    forType: ['home', 'shop'],
    inStock: true,
  },
  {
    id: 'v6',
    name: 'Business Growth Kit',
    nameHindi: 'व्यापार वृद्धि किट',
    category: 'vastu',
    subCategory: 'Business',
    price: 3999,
    originalPrice: 6499,
    discount: 38,
    rating: 4.8,
    reviews: 89,
    image: './images/puja-kit.jpg',
    images: ['./images/puja-kit.jpg'],
    description: 'Supercharge your business growth with this premium Vastu kit designed for entrepreneurs and business owners.',
    includes: ['Vyapar Vridhi Yantra', 'Mercury Shivling', 'Gomti Chakra Set', 'Business Growth Incense', 'Prosperity Crystal Grid', 'Success Mantra Book'],
    benefits: ['Boosts business revenue', 'Attracts new customers', 'Removes business obstacles', 'Enhances reputation', 'Ensures steady growth'],
    instructions: ['Place Yantra in cash counter area', 'Keep Shivling in north', 'Distribute Gomti Chakras at 4 corners', 'Light incense at opening time', 'Read success mantras daily'],
    tags: ['business', 'vastu', 'growth'],
    isNew: true,
    forType: ['business', 'shop'],
    inStock: true,
  },
  {
    id: 'v7',
    name: 'Pyramid Energy Kit',
    nameHindi: 'पिरामिड ऊर्जा किट',
    category: 'vastu',
    subCategory: 'Energy',
    price: 1799,
    originalPrice: 2999,
    discount: 40,
    rating: 4.5,
    reviews: 143,
    image: './images/vastu-kit.jpg',
    images: ['./images/vastu-kit.jpg'],
    description: 'Harness the ancient power of pyramids to balance and enhance energy flow in your living space.',
    includes: ['9 Pyramid Vastu Set', 'Center Pyramid (Large)', 'Directional Pyramids (8 pcs)', 'Energy Grid Mat', 'Compass', 'Placement Guide'],
    benefits: ['Balances energy flow', 'Enhances meditation', 'Improves sleep quality', 'Reduces stress', 'Amplifies positive energy'],
    instructions: ['Use compass to find directions', 'Place grid mat in center of room', 'Position large pyramid at center', 'Place directional pyramids correctly', 'Activate with provided mantras'],
    tags: ['pyramid', 'vastu', 'energy'],
    forType: ['home', 'office'],
    inStock: true,
  },
  {
    id: 'v8',
    name: 'Vastu for Shop Kit',
    nameHindi: 'दुकान वास्तु किट',
    category: 'vastu',
    subCategory: 'Shop',
    price: 2299,
    originalPrice: 3799,
    discount: 39,
    rating: 4.7,
    reviews: 178,
    image: './images/puja-kit.jpg',
    images: ['./images/puja-kit.jpg'],
    description: 'Specially designed for retail shops and commercial spaces to attract more customers and increase sales.',
    includes: ['Shop Vastu Yantra', 'Welcome Swastik', 'Customer Attraction Crystal', 'Cash Box Energizer', 'Entrance Purifier', 'Daily Mantra Card'],
    benefits: ['Attracts more customers', 'Increases daily sales', 'Creates positive shop energy', 'Enhances brand image', 'Ensures repeat customers'],
    instructions: ['Fix Swastik at shop entrance', 'Place Yantra behind cash counter', 'Keep crystal near billing area', 'Energize cash box on Thursdays', 'Recite daily mantra at shop opening'],
    tags: ['shop', 'vastu', 'business'],
    forType: ['shop', 'business'],
    inStock: true,
  },
  // PUJA KITS
  {
    id: 'p1',
    name: 'Satyanarayan Puja Kit',
    nameHindi: 'सत्यनारायण पूजा किट',
    category: 'puja',
    subCategory: 'Regular Puja',
    price: 1299,
    originalPrice: 1999,
    discount: 35,
    rating: 4.9,
    reviews: 567,
    image: './images/puja-kit.jpg',
    images: ['./images/puja-kit.jpg', './images/vastu-kit.jpg'],
    description: 'Complete Satyanarayan Puja Kit with all authentic items for performing the sacred puja at home.',
    includes: ['Satyanarayan Photo Frame', 'Puja Thali Set', 'Panchamrit Ingredients', 'Banana Leaves', 'Sacred Thread', 'Roli & Chawal', 'Prasad Mix', 'Dhoop & Agarbatti', 'Camphor', 'Instruction Manual with Katha'],
    benefits: ['Fulfills wishes', 'Brings family harmony', 'Ensures divine blessings', 'Removes obstacles', 'Brings prosperity'],
    instructions: ['Fast on puja day', 'Set up puja area with clean cloth', 'Place photo frame and kalash', 'Follow step-by-step katha book', 'Distribute prasad to 5 families'],
    tags: ['puja', 'satyanarayan', 'bestseller'],
    isBestseller: true,
    forType: ['home'],
    inStock: true,
  },
  {
    id: 'p2',
    name: 'Ganesh Puja Kit',
    nameHindi: 'गणेश पूजा किट',
    category: 'puja',
    subCategory: 'Festival',
    price: 999,
    originalPrice: 1599,
    discount: 37,
    rating: 4.8,
    reviews: 445,
    image: './images/vastu-kit.jpg',
    images: ['./images/vastu-kit.jpg'],
    description: 'Premium Ganesh Puja Kit for Ganesh Chaturthi and regular Ganpati worship with eco-friendly clay idol.',
    includes: ['Eco-Friendly Ganesh Idol', 'Modak Mould', 'Durva Grass', 'Red Flowers', 'Sindoor', 'Puja Thali', 'Laddu Gopal Dress', 'Aarti Book', 'Bell'],
    benefits: ['Removes obstacles', 'Brings wisdom', 'Ensures new beginnings', 'Attracts success', 'Protects family'],
    instructions: ['Install idol facing east', 'Offer durva grass first', 'Apply sindoor on forehead', 'Offer 21 modaks', 'Perform aarti morning and evening', 'Visarjan on designated day'],
    tags: ['puja', 'ganesh', 'festival'],
    isFestivalSpecial: true,
    forType: ['home'],
    inStock: true,
  },
  {
    id: 'p3',
    name: 'Lakshmi Puja Kit',
    nameHindi: 'लक्ष्मी पूजा किट',
    category: 'puja',
    subCategory: 'Wealth Puja',
    price: 1499,
    originalPrice: 2499,
    discount: 40,
    rating: 4.9,
    reviews: 389,
    image: './images/puja-kit.jpg',
    images: ['./images/puja-kit.jpg'],
    description: 'Invoke Goddess Lakshmi\'s blessings with this premium puja kit for wealth, prosperity, and abundance.',
    includes: ['Lakshmi Idol (Brass)', 'Lotus Flowers (Artificial)', 'Gold Coins Set', 'Lakshmi Yantra', 'Premium Agarbatti', 'Kumkum & Haldi', 'Red Chunari', 'Puja Vidhi Book'],
    benefits: ['Attracts wealth', 'Brings financial stability', 'Blesses with prosperity', 'Removes poverty', 'Ensures abundance'],
    instructions: ['Clean puja area thoroughly', 'Place Lakshmi idol on red cloth', 'Arrange lotus flowers around idol', 'Light lamp with ghee', 'Recite Lakshmi Chalisa', 'Offer gold coins symbolically'],
    tags: ['puja', 'lakshmi', 'wealth', 'bestseller'],
    isBestseller: true,
    forType: ['home', 'business'],
    inStock: true,
  },
  {
    id: 'p4',
    name: 'Navratri Puja Kit',
    nameHindi: 'नवरात्रि पूजा किट',
    category: 'puja',
    subCategory: 'Festival',
    price: 1799,
    originalPrice: 2999,
    discount: 40,
    rating: 4.7,
    reviews: 234,
    image: './images/vastu-kit.jpg',
    images: ['./images/vastu-kit.jpg'],
    description: 'Complete 9-day Navratri puja kit with items for each day\'s worship of Goddess Durga\'s nine forms.',
    includes: ['9 Color Chunaris', 'Durga Idol', 'Akhand Jyoti Set', 'Daily Offering Items', 'Kumkum Set (9 colors)', 'Coconuts (9)', 'Garland Set', 'Navratri Katha Book', 'Havan Samagri'],
    benefits: ['Divine mother\'s blessings', 'Destroys negativity', 'Brings courage', 'Fulfills desires', 'Spiritual awakening'],
    instructions: ['Start on Pratipada tithi', 'Establish Kalash on Day 1', 'Change chunari color daily', 'Perform daily aarti', 'Fast for 9 days', 'Kanya pujan on Ashtami/Navami'],
    tags: ['puja', 'navratri', 'festival'],
    isFestivalSpecial: true,
    forType: ['home'],
    inStock: true,
  },
  {
    id: 'p5',
    name: 'Rudrabhishek Kit',
    nameHindi: 'रुद्राभिषेक किट',
    category: 'puja',
    subCategory: 'Shiva Puja',
    price: 2199,
    originalPrice: 3499,
    discount: 37,
    rating: 4.8,
    reviews: 167,
    image: './images/puja-kit.jpg',
    images: ['./images/puja-kit.jpg'],
    description: 'Sacred Rudrabhishek Kit for performing powerful Shiva puja with authentic abhishek materials.',
    includes: ['Shivling (Narmadeshwar)', 'Abhishek Pot (Brass)', 'Bilva Patra', 'Raw Milk Container', 'Honey Jar', 'Gangajal', 'Dhatura Flowers', 'Rudraksha Mala', 'Vibhuti', 'Puja Guide'],
    benefits: ['Destroys sins', 'Brings peace of mind', 'Heals diseases', 'Removes fear', 'Grants moksha'],
    instructions: ['Wake up at Brahma Muhurta', 'Bathe and wear white clothes', 'Place Shivling on altar', 'Perform abhishek with 5 liquids', 'Offer bilva patra', 'Chant Om Namah Shivaya 108 times'],
    tags: ['puja', 'shiva', 'rudrabhishek'],
    forType: ['home'],
    inStock: true,
  },
  {
    id: 'p6',
    name: 'Shradh Puja Kit',
    nameHindi: 'श्राद्ध पूजा किट',
    category: 'puja',
    subCategory: 'Ancestor Puja',
    price: 999,
    originalPrice: 1699,
    discount: 41,
    rating: 4.6,
    reviews: 98,
    image: './images/vastu-kit.jpg',
    images: ['./images/vastu-kit.jpg'],
    description: 'Complete Shradh ceremony kit for performing ancestral rituals with devotion and authenticity.',
    includes: ['Pind Daan Items', 'Black Sesame Seeds', 'Barley', 'Kusha Grass', 'Sacred Water Vessel', 'White Cloth', 'Offering Thali', 'Ritual Guide Book'],
    benefits: ['Appeases ancestors', 'Removes Pitru Dosh', 'Brings family peace', 'Ensures ancestral blessings', 'Clears karmic debts'],
    instructions: ['Perform during Shradh period', 'Face south during ritual', 'Prepare pind with listed items', 'Offer water with sesame seeds', 'Feed Brahmins and cows', 'Donate to charity'],
    tags: ['puja', 'shradh', 'ancestors'],
    forType: ['home'],
    inStock: true,
  },
  {
    id: 'p7',
    name: 'Diwali Puja Kit',
    nameHindi: 'दिवाली पूजा किट',
    category: 'puja',
    subCategory: 'Festival',
    price: 2499,
    originalPrice: 3999,
    discount: 37,
    rating: 4.9,
    reviews: 678,
    image: './images/puja-kit.jpg',
    images: ['./images/puja-kit.jpg'],
    description: 'Grand Diwali Puja Kit for Lakshmi-Ganesh worship with premium quality items and festive decorations.',
    includes: ['Lakshmi-Ganesh Idol Set', 'Silver Coin', 'Premium Diyas (21 pcs)', 'Rangoli Stencils', 'Marigold Garlands', 'Mishri & Dry Fruits', 'Puja Thali (Decorated)', 'LED String Lights', 'Account Book (Bahi Khata)', 'Complete Puja Samagri'],
    benefits: ['Lakshmi-Ganesh blessings', 'Financial prosperity all year', 'Removes darkness of ignorance', 'Family togetherness', 'New financial beginnings'],
    instructions: ['Clean entire house before Diwali', 'Make rangoli at entrance', 'Place idols on red cloth', 'Light 21 diyas at sunset', 'Perform Lakshmi-Ganesh aarti', 'Open new account book', 'Distribute sweets'],
    tags: ['puja', 'diwali', 'festival', 'bestseller'],
    isBestseller: true,
    isFestivalSpecial: true,
    forType: ['home', 'business', 'shop'],
    inStock: true,
  },
  {
    id: 'p8',
    name: 'Monthly Home Puja Kit',
    nameHindi: 'मासिक गृह पूजा किट',
    category: 'puja',
    subCategory: 'Monthly',
    price: 699,
    originalPrice: 999,
    discount: 30,
    rating: 4.7,
    reviews: 312,
    image: './images/vastu-kit.jpg',
    images: ['./images/vastu-kit.jpg'],
    description: 'Monthly subscription puja kit with fresh items delivered to your doorstep for daily worship.',
    includes: ['Premium Agarbatti (30 packs)', 'Camphor Tablets (50 pcs)', 'Cotton Wicks', 'Kumkum & Haldi', 'Ghee (Pure Cow)', 'Flower Seeds', 'Prasad Mix', 'Monthly Panchang Calendar'],
    benefits: ['Never run out of puja items', 'Fresh quality guaranteed', 'Saves time and money', 'Ensures daily worship', 'Monthly spiritual guidance'],
    instructions: ['Items designed for 30 days use', 'Light agarbatti during morning puja', 'Use camphor for evening aarti', 'Prepare prasad with provided mix', 'Follow panchang for special days'],
    tags: ['puja', 'monthly', 'subscription'],
    forType: ['home'],
    inStock: true,
  },
];

export const reviews: Review[] = [
  { id: 'r1', userName: 'Rajesh Sharma', rating: 5, comment: 'Amazing kit! Everything was well packed and authentic. The instructions were very clear. Noticed positive changes within a week.', date: '2024-01-15', verified: true },
  { id: 'r2', userName: 'Priya Gupta', rating: 5, comment: 'Best quality puja items I have ever received. The brass items are genuine and the packaging was premium. Highly recommended!', date: '2024-01-10', verified: true },
  { id: 'r3', userName: 'Amit Patel', rating: 4, comment: 'Good quality products. Delivery was on time. The instruction booklet was very helpful for performing the puja correctly.', date: '2024-01-08', verified: true },
  { id: 'r4', userName: 'Sunita Devi', rating: 5, comment: 'मैंने यह किट अपने नए घर के लिए खरीदी। बहुत अच्छी quality है। सब authentic items हैं।', date: '2024-01-05', verified: true },
  { id: 'r5', userName: 'Vikram Singh', rating: 5, comment: 'Outstanding! The vastu kit has truly transformed the energy of my office. Business has improved noticeably.', date: '2024-01-03', verified: true },
];

export const quizQuestions: QuizQuestion[] = [
  { id: 1, question: 'What type of property do you want the remedy for?', options: ['House/Flat', 'Office', 'Shop/Showroom', 'Factory/Warehouse'] },
  { id: 2, question: 'Which direction does your main entrance face?', options: ['North', 'South', 'East', 'West', 'Not Sure'] },
  { id: 3, question: 'What is the main problem you are facing?', options: ['Financial Issues', 'Health Problems', 'Relationship Issues', 'Career Stagnation', 'Negative Energy', 'Multiple Issues'] },
  { id: 4, question: 'How long have you been facing this issue?', options: ['Less than 6 months', '6 months - 1 year', '1-3 years', 'More than 3 years'] },
  { id: 5, question: 'Have you tried any Vastu remedy before?', options: ['No, first time', 'Yes, basic remedies', 'Yes, professional consultation', 'Yes, but didn\'t work'] },
  { id: 6, question: 'What is your budget range?', options: ['Under ₹1,500', '₹1,500 - ₹3,000', '₹3,000 - ₹5,000', 'Above ₹5,000'] },
];

export const dailyTips: DailyTip[] = [
  { id: 't1', title: 'Entrance Direction', content: 'Keep your main entrance well-lit and clutter-free. A clean entrance attracts positive energy and prosperity.', category: 'Vastu', icon: '🚪' },
  { id: 't2', title: 'Kitchen Placement', content: 'The ideal placement for kitchen is the Southeast corner. Always face East while cooking for positive energy.', category: 'Vastu', icon: '🍳' },
  { id: 't3', title: 'Morning Mantra', content: 'Start your day with "Om Gam Ganapataye Namaha" 11 times to remove obstacles and bring success.', category: 'Mantra', icon: '🕉️' },
  { id: 't4', title: 'Money Corner', content: 'Place a money plant in the Southeast corner of your home. Water it regularly for financial growth.', category: 'Prosperity', icon: '💰' },
  { id: 't5', title: 'Bedroom Peace', content: 'Never place a mirror facing the bed. It disturbs sleep and can cause relationship issues.', category: 'Vastu', icon: '🛏️' },
  { id: 't6', title: 'Evening Ritual', content: 'Light a ghee diya in the evening at your puja space. It purifies the atmosphere and brings divine energy.', category: 'Ritual', icon: '🪔' },
];

export const subscriptions: Subscription[] = [
  {
    id: 'sub1',
    name: 'Monthly Puja Essentials',
    price: 699,
    frequency: 'Monthly',
    description: 'Never run out of daily puja items. Fresh and authentic supplies delivered every month.',
    features: ['30 days supply', 'Premium agarbatti', 'Pure cow ghee', 'Camphor & wicks', 'Monthly panchang', 'Free delivery'],
  },
  {
    id: 'sub2',
    name: 'Festival Special Box',
    price: 1299,
    frequency: 'Quarterly',
    description: 'Special puja kits curated for upcoming festivals. Never miss a festival celebration.',
    features: ['Festival-specific items', 'Decoration materials', 'Prasad ingredients', 'Step-by-step guide', 'Festival calendar', 'Priority delivery'],
  },
  {
    id: 'sub3',
    name: 'Premium Spiritual Box',
    price: 2499,
    frequency: 'Monthly',
    description: 'The ultimate spiritual experience. Premium items, exclusive content, and personalized guidance.',
    features: ['Premium puja items', 'Rare spiritual items', 'Personal Vastu tip', 'Exclusive mantras', 'Priority consultation', 'Free express delivery'],
  },
];
